### ISSUE TITLE
BMS Tool links missing

### ISSUE THREAD

**Issue by isocosa** [BMS-Community/resources#1]
These tools are missing:

- [x] BMHelper (non-english version)
- [x] BGAEncAdv
- [x] ~~uBMplay Windows 7-10 Fix~~

If anyone has those, please reupload them.

**Comment by bonjorno7** [comment]
Ignore my edit, was an accident

**Comment by bonjorno7** [comment]
Okay apparently we're not doing uBMplay because AYhaz says it doesn't matter

**Comment by bonjorno7** [comment]
Btw I found BMHelper Japanese so that's done at least.

**Comment by bonjorno7** [comment]
BGAEncAdv has been posted in #resources
