### ISSUE TITLE
Some 5-key event packs to add

### ISSUE THREAD

**Issue by isocosa** [BMS-Community/resources#13]
AFAIK those are most popular 5key event packs but apparently they're not on the list.

- [x] plugout1
- [x] plugout3
- [x] Diverse System Presents [db]

They are tricky to find so..,

**Comment by BMSworld** [comment]
Would you consider adding my website, BMSworld.NZ to this resource?

**Comment by SayakaIsBaka** [comment]
Reviving this extremely old issue
plugout1 and 3 are already available on package.bms.ms, I'll add db as it is still available on the official website

**Comment by SayakaIsBaka** [comment]
Website has been updated.
